### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by GRitchie1** [MatthewCroughan/octobalena#38]
Getting the following build error using the balena deploy:

ERROR: The command '/bin/sh -c pip3 install aiohttp aiortc numpy opencv-python' returned a non-zero code: 1

The build fails due to this error.

Regards,
Gregor

**Comment by dhumphrey7** [comment]
It appears this line was added when MattaCloud was added as a plugin.  Mattacloud was then removed a day later but this line was left in.  I cloned the repo and commented out this line in the Dockerfile.raspberrypi3 file, after this it built successfully.  Will flash the new device image to the pi when I get home and see if everything else worked.

**Comment by GRitchie1** [comment]
Thanks, I'll give it a try also.

**Comment by GRitchie1** [comment]
This allowed it to build successfully, but the container now won't start.  I'm getting the following error on the balena logs:

 octoprint  Command not found: /app/udevd.sh

**Comment by dhumphrey7** [comment]
When you created the balena app you created it as Raspberry3?  I was able to get this is run by selecting RPi3 and as the app and then selecting the device as a RPI4 (since I am using a 4).  Everything booted fine on the pi, but when I access octoprint via the web browser I am unable to complete the wizard now.  When I click the finish button this is the error I  get.

`10.02.21 17:36:16 (-0600)  octoprint  2021-02-10 23:36:16,953 - octoprint - ERROR - Exception on /api/settings [POST]
10.02.21 17:36:16 (-0600)  octoprint  Traceback (most recent call last):
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
10.02.21 17:36:16 (-0600)  octoprint      response = self.full_dispatch_request()
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
10.02.21 17:36:16 (-0600)  octoprint      rv = self.handle_user_exception(e)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
10.02.21 17:36:16 (-0600)  octoprint      reraise(exc_type, exc_value, tb)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
10.02.21 17:36:16 (-0600)  octoprint      raise value
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
10.02.21 17:36:16 (-0600)  octoprint      rv = self.dispatch_request()
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
10.02.21 17:36:16 (-0600)  octoprint      return self.view_functions[rule.endpoint](**req.view_args)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/octoprint/server/util/flask.py", line 1539, in decorated_view
10.02.21 17:36:16 (-0600)  octoprint      return func(*args, **kwargs)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/octoprint/vendor/flask_principal.py", line 199, in _decorated
10.02.21 17:36:16 (-0600)  octoprint      rv = f(*args, **kw)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/octoprint/server/api/settings.py", line 388, in setSettings
10.02.21 17:36:16 (-0600)  octoprint      response = _saveSettings(data)
10.02.21 17:36:16 (-0600)  octoprint    File "/usr/local/lib/python3.7/dist-packages/octoprint/server/api/settings.py", line 936, in _saveSettings
10.02.21 17:36:16 (-0600)  octoprint      "gcode", name, script.replace("\r\n", "\n").replace("\r", "\n")
10.02.21 17:36:16 (-0600)  octoprint  AttributeError: 'NoneType' object has no attribute 'replace'
10.02.21 17:36:16 (-0600)  octoprint  2021-02-10 23:36:16,958 - tornado.access - ERROR - 500 POST /api/settings (::ffff:192.168.1.51) 83.39ms
`

**Comment by dhumphrey7** [comment]
I went ahead and rebuild the image using the latest version of octoprint.  Still had same error.  Used http://octoip/recovery and set the server to restart in safe mode.  Manually restarted the octoprint service in balena as the killall -15 supervisord command does not work.  Finished the first time wizard and then manually restarted service again.  After all of this the service is running.  Will be working on getting camera working next.

**Comment by GRitchie1** [comment]
I created the application under RPi3, and my device is also a RPi3.  I will try again later on today.
